name: "Set Assignee"
on:
  issues:
    branches-ignore:
        - '**'
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '[" "]'
          assignees: '["urapadmin"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
