name: Add Assignees

on:
  issues:
    types: [opened]

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add assignees using GitHub CLI
        # Notice the space instead of a comma between the assignees 👇
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee "urapadmin" --add-assignee "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
